[package]
name = "bitcoin-alerts"
version = "0.1.0"
edition = "2021"
authors = ["Yuki Kishimoto <yukikishimoto@proton.me>"]
homepage = "https://github.com/yukibtc/bitcoin-alerts"
repository = "https://github.com/yukibtc/bitcoin-alerts.git"
license = "MIT"
readme = "README.md"
rust-version = "1.64"
keywords = ["bitcoin", "alerts", "notifications"]

[dependencies]
bitcoin = "0.30"
bitcoin-rpc = { git = "https://github.com/yukibtc/bitcoin-rpc", rev = "49b264519742a44207ada56d8e1883f1e15ae347" }
clap = { version = "4.4", features = ["derive"] }
dirs = "5.0"
lazy_static = "1.4"
nostr-sdk = { version = "0.28", default-features = false }
ntfy = "0.3"
num_cpus = "1.16"
rocksdb = { version = "0.21", default-features = false, features = ["multi-threaded-cf", "zstd"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tokio-stream = "0.1"
toml = "0.5"
tracing = "0.1"
tracing-subscriber = "0.3"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"