##
## Bitcoin Alerts configuration file. Lines beginning with # are comments.
##

# Directory where data should be stored (default: ~/.bitcoin_alerts)
# main_path = "/path/to/save/bitcoin-alerts/data"

# Console log level: TRACE, DEBUG, INFO, WARN, ERROR (default: INFO)
# log_level = "INFO"

[bitcoin]
# Network: bitcoin, testnet, regtest, signet (default: bitcoin) - don't set to anything else unless you're a developer
# network = "bitcoin"  

# Bitcoin RPC host and port (default: 127.0.0.1:8332)
# rpc_addr = "127.0.0.1:8332"  

# Bitcoin RPC username
rpc_username = "yourusername"

# Bitcoin RPC password
rpc_password = "yourpassword"  

[ntfy]
# Enable ntfy notifications (default: false)
# enabled = false      

# Ntfy server url
# url = "https://example.com"    

# Ntfy topic (default: bitcoin_alerts)
# topic = "bitcoin_alerts"

# Credentials (default: None)
# username = "username"
# password = "password"

# Needed if you want use onion url (default: None)
# proxy = "socks5h://127.0.0.1:9050"

[nostr]
# Enable nostr post (default: false)
# enabled = false   

# Nostr secret key (bech32 or hex format)
# secret_key = "nsec1..."

# Name
# name = "bitcoin_alerts"

# Display name
# display_name = "Bitcoin Alerts"

# Description
# description = "Hashrate, supply, blocks until halving, difficulty adjustment and more.\n\nBuilt with https://crates.io/crates/nostr-sdk 🦀"

# Picture
# picture = "https://avatars.githubusercontent.com/u/13464320"

# NIP05
# nip05 = "bitcoin_alerts@example.com"

# LUD16 (Lightning Address)
# lud16 = "yuki@getalby.com"

# Nostr relays
# relays = ["wss://relay1.example", "ws://127.0.0.1:8090"]

# POW difficulty (default: 0)
# pow_difficulty = 0
