##
## Bitcoin Alerts configuration file. Lines beginning with # are comments.
##

# main_path = "/path/to/save/bitcoin-alerts/data"     # (Optional) Directory where data should be stored (default: ~/.bitcoin_alerts)

[bitcoin]
# rpc_addr = "127.0.0.1:8332"               # (Optional) Bitcoin Core RPC host and port (default: 127.0.0.1:8332)
rpc_username = "yourusername"               # Bitcoin Core RPC username
rpc_password = "yourpassword"               # Bitcoin Core RPC password

[matrix]
homeserver_url = "http://localhost:8008"    # Your local, onion or clearnet homeserver url
# proxy = "socks5h://127.0.0.1:9050"        # (Optional) Needed if you want use onion homeserver url (default: None)
user_id = "@username:example.com"           # Matrix Bot user_id
password = "yourpassword"                   # Matrix Bot password
admins = ["@admin:example.com", "@admin2:example.com"]